### ISSUE TITLE
Auto-generate pages on check-in

### ISSUE THREAD

**Issue by schuster** [nuprl/nuprl.github.io#16]
Maybe use Travis or something similar?

**Comment by wilbowma** [comment]
Could use git-hooks to build locally before commits.

**Comment by bennn** [comment]
@gasche here's an idea to avoid committing generated files
1. Keep the `master` branch as-is, with generated files committed to it.
2. Create a new branch `blog-master` or `dev` that ignores generated files
3. Set the new branch as the default branch.
4. Contributor PRs go to the new branch; maintainers need to move commits to `master` & build the site.

Any objections to sending ALL pull requests to a non-master branch by default?

**Comment by gasche** [comment]
I'm fine with this plan. Its practicality also depends on how the github UI reacts to having a branch named `master` that is not the default branch -- it would be very convenient if the "create pull request" would use `dev` by default, otherwise I think people would forget about the distinction and maintainers would have to cherry-pick commits into the right branch after-the-fact.

**Comment by bennn** [comment]
If `dev` is the default branch then pull requests automatically target `dev`.

**Comment by gasche** [comment]
Then let's do it!

**Comment by schuster** [comment]
Isn't this just shifting the problem around rather than solving it? It wouldn't automate the build process, but require someone else to do it instead. Plus won't authors want to install and run frog anyway to see their posts while writing it? Esp. if using code snippets, I can't imagine they'll want to submit without having seen the final product first. So I'm not sure this removes the barrier to entry.

I think there are really two separate issues here:
1. Should there be an _automated_ process that re-generates the site for every checkin? That's what this issue was originally about, and I think the answer should be yes.
2. Should we have a separate "editor" role for the blog who checks over posts before they're published? I'm not convinced this is necessary. Anyone who doesn't already have commit access to the site has to submit a PR, and I would generally trust lab members who do have commit access to only publish "good" things or voluntarily ask for feedback first.

**Comment by gasche** [comment]
The main problem that I think is worth solving is having to commit the generated files.
- In terms of DCVS I think it is morally wrong to commit generated files (they have no useful versioning information); you could say we are just shifting this issue around by moving them to a separate branch, but the way I think of it is that `dev` would be the blog (as a collection of source documents) and that `master` becomes just an implementation detail, a particular release/deployment tools for blog administrators, that I (mere contributor/author) don't have to know or think about.
- Having generated-files commits interleaved with source commits obscure the change history and makes it harder to work with. In particular, when we actually make changes to the web sources of the blog (template files, CSS files, html snippets etc.), it is important to keep these changes versioned and visible, and currently they are kind of hidden in the middle of generated file noise.
- Finally, committing the generated files is actually _surprisingly tricky_. Some of them are already in the git index, so it's just a matter of doing `git add --all` and their changes will be recorded (note that this has the downside that it's easy to accidentally commit both sources and generated files in the same commit, another change that obscures real edition history). But a lot of them are generated anew for each blog post (for example when a new tag appear, a new `.html` file is created), and my personal technique to commit them is something like (from memory) `git status | grep -o "[a-zA-Z/.-]*.html" | xargs git add`, not exactly user-friendly (does someone know of a command to make this easier?). On my first post I actually forgot about those files and my "generated files" commit was wrong, forcing Ben to re-do the work properly.

Note that the proposed organization does not impose the presence of maintainers/editors/curators: if we want to automatize the build and deployment processes, it won't be harder to do with the new proposed workflow than it was for the previous one -- that is, supposing that whichever scripting hook we use allows to change branches and perform new commits; I'm assuming they actually allow this, but maybe I'm wrong on that. I personally think that having maintainers with a special role in the publication process is fine, but we can revisit this choice if it appears to be a bottleneck in the blog writing process.

**Comment by bennn** [comment]
Right,
- `dev` would just be source code. Contributors should build the site before pushing, but `dev` would not contain any generated files (and have a clean history, easy-to-read diffs, ...).
- `master` would be source code and generated files. Because I think we need to commit the generated files for Github to host them.

And we can add a git hook so that all commits to master (i.e. merge commits) rebuild the site. Though, I like the idea that whoever merges is also makes sure the site looks OK rather than trusting the automated build.

**Comment by schuster** [comment]
I'm not terribly convinced that keeping version history clean is all that important for a simple website like this, especially since (I think) one can just mentally follow the simple rule of "ignore all changes to .html files" to get the real changes.

I guess I would think that adding the generated files would be a matter of using whatever command git has to say "add _all_ new or changed files in the current working directory to the index", but perhaps I'm missing something. I use [magit](https://magit.vc/) for all of my git commits, so I don't know how hard this is using, say, the command line.

Primarily I'm just worried about adding more manual effort to the site, but if I'm the only one raising the concern, then maybe it's not a big deal. If the build process gets automated then that solves the issue no matter what; it's just a matter of someone spending the effort to figure out how to do that and implement it.

**Comment by dbp** [comment]
To re-open this conversation - is there a reason why we care about having the generated files in git? Is it just so that we can use github pages? Are we that attached to that? I've made a bunch of sites with static site generators, and in every case have stored the generated files on S3, and just have the source in git. Then master automatically builds & deploys, so any work that gets merged gets deployed. 

Aside from the logistics of actually getting a real AWS account (ie, probably has to have some credit card attached), there is no monetary difference between github pages (actually free) and S3 at this scale (since it is essentially free).

You can, of course, still build locally to preview things, but in general this setup has been super simple, as there aren't multiple branches or any steps beyond pull requests. It also means you don't _need_ to have a local setup of frog (though you probably usually would want one).

The entire setup involves creating the S3 bucket w/ public read perms, generating credentials to write to it, storing the credentials with the CI service (I was using Circle, but Travis should be similar), and writing a few lines of config (included here). This used Jekyll, but installing racket / frog shouldn't be very different.

```
dependencies:
  override:
    - gem install jekyll:2.5.2 git:1.2.9.1
    - sudo pip install awscli

test:
  override:
    - echo 0

deployment:
  aws:
    branch: master
    commands:
      - jekyll build
      - aws s3 sync _site s3://www.website.com
```

**Comment by bennn** [comment]
Yes, we only check in generated files because we're using github pages.

I like the S3 idea. Let's ask Jan for his credit card.

**Comment by schuster** [comment]
I agree - if Jan or someone else is cool paying for an AWS instance, this would be a much better option than what we do now.

**Comment by dbp** [comment]
Since it'll just be S3, it should be very cheap (or free; I think it's
$0.09/G traffic, first one free. First year it's first 15G free... do we
have any sense of traffic?).

**Comment by schuster** [comment]
No idea on traffic - I can't seem to find any info on getting traffic numbers from GitHub Pages.

**Comment by gasche** [comment]
So @benm just asked Jan and he seemed unconvinced by the need for S3. Which is actually a fair reaction (although I was also enthusiastic about @dbp's proposal initially): what does it actually give us over what we have?

I think the actual added value of @dbp's workflow over the current one is the CI-time (Continuous Integration) automation of the rendering. So what we want is a solution where pushing to the github repo automatically rebuilds (or else a cron that rebuilds regularly, but it's not as nice). So let's assume this is what we want for now: what's the easiest way to get it? It may be to just enable some form CI on github and put Daniel's magic in it.

Who is volunteering to experiment with that?

**Comment by dbp** [comment]
The advantage is that we don't need to store the artifacts in the same
repository as the source. S3 is immaterial - any place we could host files
and have them served would work.

But yes, we could have CI build from src and push to master, it just still
means we have this src/master dichotomy which seems somewhat confusing
(github somewhat let us set a different branch as default, but for example
milo got confused by it and tried to pull req into master).

Actually - does github pages require that master is what is served? Because
if we could have a non-master branch that was just the artifacts and then
set up CI to push to that I think that'd be essentially perfect.

**Comment by schuster** [comment]
Yes, apparently you can set up a `gh-pages` branch instead: https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

**Comment by mhyee** [comment]
GitHub provides [webhooks](https://developer.github.com/webhooks/), so that whenever you push to the repository (or some other event), GitHub will send an HTTP POST request to the configured URL. So no need for cron.

**Comment by dbp** [comment]
I can work on this. Plan would be to:
1. Create gh-pages branch
2. Set up CI to trigger on commits to src, build and push artifact to
   gh-pages
3. Switch github to serve gh-pages branch rather than master
4. Force master to be src, make it default branch again, etc
5. Switch CI to build master commits, not src ones
6. Delete src branch

Thoughts?

**Comment by schuster** [comment]
@dbp Love it. Once this is running, I just recommend you document the CI infrastructure in the README (where the VM is, how the webhooks are set up, etc.) since otherwise that information is not contained in the repository.

**Comment by dbp** [comment]
Yeah - Travis/circle use GitHubs API to set those up. They also feed info
back about success/failure.

**Comment by mhyee** [comment]
Actually, are we _sure_ that we can use a `gh-pages` branch? From looking at [this page](https://help.github.com/articles/user-organization-and-project-pages/), it seems like we can't, because this is an organization page and not a project page. :(

**Comment by gasche** [comment]
Github rules on webpage are inflexible and generally inconvenient. We can always use two separate repos if required.

**Comment by schuster** [comment]
Ugh. F-ing GitHub.

A separate repo would be nice, but does anyone know what it would take to redirect prl.ccs.neu.edu to github.com/nuprl.github.io/our-website? I don't think just DNS redirects alone can deal with sub-directory URLs.

**Comment by gasche** [comment]
No but we can easily move the _source_ repo somewhere else. Then we just need to give the correct URL (and it can be prominent in the README as well).

**Comment by schuster** [comment]
Good point, that should work.

**Comment by dbp** [comment]
Okay, new plan:
1. create `website` repository. Push current `src` branch to `master` there.
2. set up CI to build that repository and then push to `master` on current repo.
3. change docs etc to get people to use the new repo instead.

**Comment by schuster** [comment]
:+1:

**Comment by dbp** [comment]
Okay, so I think this is all set up. It was good to be reminded why I dislike engineering :)

General setup is as I outlined, and there is a new SETUP.md doc in the new source repo describing some, but there are a few details:

The history on the artifact repo will _not_ include the history of the source https://github.com/nuprl/website repo. Each deploy will have a single commit, which contains all the changes in that deploy (which will usually be the entire contents of a pull request and the changes in the built artifacts). The commit message will have a link back to the source commit that this corresponds to. This means that you can look through the history of the artifact repo and easily see every state of the website (it'd also make emergency reverts possible, even if the whole build infrastructure is non-functional).

You can see this in action by looking at the `master_test` branch: https://github.com/nuprl/nuprl.github.io/commits/master_test

Could y'all check it out and see if anything seems off? You can see it hosted here:

https://rawgit.com/nuprl/nuprl.github.io/master_test/

Provided it's right, all I need to do is switch it to point to the `master` branch, and then update documentation to point at the new https://github.com/nuprl/website repository.

**Comment by gasche** [comment]
Thanks! Looks very nice.

[the blog on master_test](https://rawgit.com/nuprl/nuprl.github.io/master_test/blog/index.html) does not exist, is that intended?

It would be nice to point to the artifact repository from website/README.md, and also the [README.md](https://github.com/nuprl/nuprl.github.io/) currently present on the artifact repo claims to be the source repository, which is a bit confusing. Could the deployment script filter that one out or replace it by, say, a README.artifact.md file we would also maintain on the source repo?

**Comment by dbp** [comment]
@gasche I may have just messed something up - regardless, I'll figure out what's wrong with the blog. (there is some trickiness to getting the history right without interactivity...)

Other suggestions sound like a great idea too.

**Comment by dbp** [comment]
Okay I fixed the blog issue (I didn't realize it used it's own `.gitignore`). There are some issues with it currently but I think that's just due to the presence of absolute urls (so it'll be fine on the live site, just broken on the rawgit thing). 

I also squashed the history (as since there is no way to directly debug travis, I had to create a bunch of minor commits). 

I can fix the READMEs once we switch, as it'll be less confusing how to do it properly. Anyone notice any other problems?

**Comment by bennn** [comment]
yeah this looks great

**Comment by dbp** [comment]
okay I'm going to make this live.

**Comment by dbp** [comment]
Okay this is done. @gasche What I decided to do is treat the README the same as the .gitignores - whatever is in the artifact repo will be kept unchanged. I put a brief description of difference, but if someone else wants to expand, they are welcome to. 

Is there somewhere that this change should be announced? Also, should we try to move the still-open issues over to the new source repository? I'd also probably like to get rid of the rest of the branches on the artifact repo.

**Comment by schuster** [comment]
I think it's a good idea to move the still-open issues over - I'm using the ones assigned to me, if nothing else.
