### ISSUE TITLE
Add instructions for merging from src

### ISSUE THREAD

**Issue by schuster** [nuprl/nuprl.github.io#52]
We should put instructions into the README on how to merge changes from the `src` branch into `master`. I just did it myself and figuring it out was a pain (partially because I hadn't dealt with git cherry-pick before).

@bennn You mentioned in https://github.com/nuprl/nuprl.github.io/pull/44#issuecomment-229148131 that you've just been using git cherry-pick, rebuilding, then commiting the auto-gen stuff. Is there some better way to do this until we switch to a full CI system? Seems like it's hard to make sure the two branches are actually consistent with each other.

**Comment by bennn** [comment]
Proposed instructions are in #53 and #55.
- It's maybe possible to sync `src` & `master` so they have different pasts but a common present/future. Then we could `git merge origin/src` on `master` instead of doing `git cherry-pick <HASH>` for every single commit.
- About the "CI", we can maybe write a [Jekyll](https://help.github.com/articles/using-jekyll-as-a-static-site-generator-with-github-pages/) file that rebuilds the site. It's messy but I can't imagine another automatic solution.

Personally I don't mind cherry-picking changes for the next 3 years or until github becomes a better host. `:p`

**Comment by schuster** [comment]
Hmm, yeah, this seems like it is the best solution for now. This still seems more complicated to me than the old single-branch approach, but as long as we've dealt with the bus-factor issue by putting instructions online, it's good enough.

Thanks for writing up the instructions. Feel free to merge the PRs whenever you think they're ready.

**Comment by bennn** [comment]
Thanks to Gabriel, life is easier now. To update the website:
- Make changes to a new branch
- Pull request the branch to `src`
- Merge the branch into `src`, make sure to make a merge commit
- Checkout `master`, run `make sync`. When prompted enter a commit message or your github passwords.

That's it, no more explicit cherry picking (unless you didn't make a merge commit).

**Comment by schuster** [comment]
Sounds great, thanks!

Closing this issue since the instructions have been merged in.
